### ISSUE TITLE
Drop with Force option

### ISSUE THREAD

**Issue by nateships** [dbsnapper/dbsnapper#3]
Would it be possible to add a drop <database> with (FORCE); option to load

--> ERROR: Could not drop and create database: ERROR: database "test" is being accessed by other users (SQLSTATE 55006)

**Comment by joescharf** [comment]
Yes, great idea. Fixed in [v2.0.3 release](https://github.com/dbsnapper/dbsnapper/releases/tag/v2.0.3)
